language: c++

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
    
    - os: osx
      osx_image: xcode9.4

before_install:
    - sudo apt-get install -y clang
    - test -n $CC  && unset CC
    - test -n $CXX && unset CXX

install:
  - git clone https://github.com/google/googletest.git && pushd googletest && mkdir build && pushd build && cmake .. && make && sudo make install && popd && popd

compiler:
  - clang

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash -c "make test_all"; fi'
