language: c++

install:
  - git clone https://github.com/google/googletest.git && pushd googletest && mkdir build && pushd build && cmake .. && make && sudo make install && popd && popd

compiler:
  - clang

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash -c "make test_all"; fi'
